In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [5]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9939 non-null   object
 6   Age              9798 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB


T**ask-1 NORMALIZATION**

**X normalized = (X – X minimum) / (X maximum – X minimum)**

In [12]:
new_df = pd.DataFrame(df, columns =['Age', 'Tenure'])

In [13]:
new_df

       Age  Tenure
0     42.0       2
1     41.0       1
2     42.0       8
3     39.0       1
4     43.0       2
...    ...     ...
9995   NaN       5
9996  35.0      10
9997  36.0       7
9998  42.0       3
9999  28.0       4

[10000 rows x 2 columns]

In [15]:
new_df['Age'] = new_df['Age'].fillna(new_df['Age'].mean())

In [16]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     10000 non-null  float64
 1   Tenure  10000 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 156.4 KB

In [17]:
scaler = MinMaxScaler()
normalized_df = scaler.fit_transform(new_df)

In [18]:
normalized_df

array([[0.32432432, 0.2       ],
       [0.31081081, 0.1       ],
       [0.32432432, 0.8       ],
       ...,
       [0.24324324, 0.7       ],
       [0.32432432, 0.3       ],
       [0.13513514, 0.4       ]])


**Task-2 STANDARDIZATION**

Formula:
           **Z = (X -μ)
            / σ**



Where:

X = value

μ = mean

σ = standard deviation

In [21]:
scaler = StandardScaler()
standardized_df = scaler.fit_transform(new_df)

In [22]:
standardized_df

array([[ 0.29740799, -1.04175968],
       [ 0.20079945, -1.38753759],
       [ 0.29740799,  1.03290776],
       ...,
       [-0.28224327,  0.68712986],
       [ 0.29740799, -0.69598177],
       [-1.05511162, -0.35020386]])